#!/bin/bash

cd build
make
cd ..

mkdir results_180

#FILENAME="path/cur_180deg_300m.txt";
#RESNAME="cur_180deg_300m";
#NUMLINES=$(wc -l < $FILENAME);
#INTERVALS=95;
#./run $FILENAME $RESNAME $NUMLINES $INTERVALS

#FILENAME="path/cur_180deg_250m.txt";
#RESNAME="cur_180deg_250m";
#NUMLINES=$(wc -l < $FILENAME);
#INTERVALS=75;
#./run $FILENAME $RESNAME $NUMLINES $INTERVALS

FILENAME="path/cur_180deg_250m.txt";
RESNAME="cur_180deg_250m_h200m";
NUMLINES=$(wc -l < $FILENAME);
INTERVALS=55;
HEIGHT=200;
./run $FILENAME $RESNAME $NUMLINES $INTERVALS $HEIGHT

FILENAME="path/cur_180deg_250m.txt";
RESNAME="cur_180deg_250m_h300m";
NUMLINES=$(wc -l < $FILENAME);
INTERVALS=55;
HEIGHT=300;
./run $FILENAME $RESNAME $NUMLINES $INTERVALS $HEIGHT

#FILENAME="path/cur_180deg_150m.txt";
#RESNAME="cur_180deg_150m";
#NUMLINES=$(wc -l < $FILENAME);
#INTERVALS=45;
#./run $FILENAME $RESNAME $NUMLINES $INTERVALS

#FILENAME="path/cur_180deg_100m.txt";
#RESNAME="cur_180deg_100m";
#NUMLINES=$(wc -l < $FILENAME);
#INTERVALS=40;
#./run $FILENAME $RESNAME $NUMLINES $INTERVALS

#FILENAME="path/cur_180deg_50m.txt";
#RESNAME="cur_180deg_50m";
#NUMLINES=$(wc -l < $FILENAME);
#INTERVALS=35;
#./run $FILENAME $RESNAME $NUMLINES $INTERVALS
