#!/bin/bash

cd build
make
cd ..

mkdir results_heights


FILENAME="path/cur_45deg_200m.txt";
RESNAME="cur_45deg_200m_h100m";
NUMLINES=$(wc -l < $FILENAME);
INTERVALS=30;
HEIGHT=100;
./run $FILENAME $RESNAME $NUMLINES $INTERVALS $HEIGHT

FILENAME="path/cur_45deg_200m.txt";
RESNAME="cur_45deg_200m_h200m";
NUMLINES=$(wc -l < $FILENAME);
INTERVALS=30;
HEIGHT=200;
./run $FILENAME $RESNAME $NUMLINES $INTERVALS $HEIGHT

FILENAME="path/cur_45deg_200m.txt";
RESNAME="cur_45deg_200m_h300m";
NUMLINES=$(wc -l < $FILENAME);
INTERVALS=30;
HEIGHT=300;
./run $FILENAME $RESNAME $NUMLINES $INTERVALS $HEIGHT

FILENAME="path/lin_45deg.txt";
RESNAME="lin_45deg_h100m";
NUMLINES=$(wc -l < $FILENAME);
INTERVALS=30;
HEIGHT=100;
./run $FILENAME $RESNAME $NUMLINES $INTERVALS $HEIGHT

FILENAME="path/lin_45deg.txt";
RESNAME="lin_45deg_h200m";
NUMLINES=$(wc -l < $FILENAME);
INTERVALS=30;
HEIGHT=200;
./run $FILENAME $RESNAME $NUMLINES $INTERVALS $HEIGHT

FILENAME="path/lin_45deg.txt";
RESNAME="lin_45deg_h300m";
NUMLINES=$(wc -l < $FILENAME);
INTERVALS=30;
HEIGHT=300;
./run $FILENAME $RESNAME $NUMLINES $INTERVALS $HEIGHT
